"""Каталог оптимизаций Calamity v2."""

from __future__ import annotations

from dataclasses import dataclass, replace
from functools import lru_cache
from typing import Callable

from boot_risk import boot_risk_recovery_line, get_boot_risk_level
from tweak_copy import TWEAK_COPY

from engine import (
    apply_audio_mmcss_pro,
    apply_auto_end_tasks,
    apply_background_apps_off,
    apply_bcd_timer_tweaks,
    apply_content_delivery_off,
    apply_core_parking_off,
    apply_cortana_off,
    apply_cursor_fast_update,
    apply_cpu_priority,
    apply_csrss_priority,
    apply_cs2_priority,
    apply_defender_off,
    apply_delivery_optimization_off,
    apply_disable_page_combining,
    apply_disable_print_spooler,
    apply_desktop_responsiveness,
    apply_disable_hpet_bcd,
    apply_disable_prefetch_gaming,
    apply_diagtrack_off,
    apply_directx_tweaks,
    apply_dns_cloudflare,
    apply_error_reporting_off,
    apply_disable_cstates,
    apply_disable_dynamic_pstate,
    apply_disable_fso_global,
    apply_disable_mpo,
    apply_disable_pointer_shadow,
    apply_disable_vbs,
    apply_distribute_timers,
    apply_dwm_animations_off,
    apply_energy_logging_off,
    apply_fth_off,
    apply_game_dvr_off,
    apply_game_mode_on,
    apply_game_profile,
    apply_gpu_energy_drv_off,
    apply_gpu_preemption,
    apply_gpu_power_latency_pack,
    apply_gpu_thread_priority,
    apply_graphics_latency,
    apply_gta5_priority,
    apply_hags,
    apply_hidusb_low_latency,
    apply_hibernate_off,
    apply_input_layered_latency,
    apply_io_page_lock_limit,
    apply_keyboard_fast_delays,
    apply_keyboard_queue_size,
    apply_latency_sensitive_games,
    apply_location_off,
    apply_maintenance_off,
    apply_memory_compression_off,
    apply_memory_gaming,
    apply_mmcss_aggressive,
    apply_monitor_latency,
    apply_mouse_1to1,
    apply_mouse_queue_size,
    apply_msi_gpu,
    apply_msi_network,
    apply_msi_usb,
    apply_ndu_off,
    apply_nic_power_off,
    apply_network_throttle_off,
    apply_notifications_off,
    apply_nvidia_driver_tweaks,
    apply_nvidia_telemetry_off,
    apply_nvidia_write_combining_off,
    apply_power_latency_pack,
    apply_power_throttling_off,
    apply_raw_input_priority,
    apply_ssd_trim,
    apply_sysmain_off,
    apply_telemetry_policies_off,
    apply_tcp_low_latency,
    apply_transparency_off,
    apply_ultimate_power_plan,
    apply_win32_priority_26,
    apply_usb_power_saving_off,
    apply_usb_selective_suspend_off,
    apply_valorant_priority,
    apply_widgets_off,
    apply_windowed_games_opt,
    apply_xbox_services_off,
    revert_audio_mmcss_pro,
    revert_auto_end_tasks,
    revert_background_apps_on,
    revert_bcd_timer_tweaks,
    revert_content_delivery_on,
    revert_core_parking_on,
    revert_cortana_on,
    revert_cursor_fast_update,
    revert_cpu_priority,
    revert_csrss_priority,
    revert_cs2_priority,
    revert_defender_on,
    revert_delivery_optimization_on,
    revert_disable_page_combining,
    revert_disable_print_spooler,
    revert_desktop_responsiveness,
    revert_disable_hpet_bcd,
    revert_disable_prefetch_gaming,
    revert_diagtrack_on,
    revert_directx_tweaks,
    revert_dns_dhcp,
    revert_error_reporting_on,
    revert_disable_cstates,
    revert_disable_dynamic_pstate,
    revert_disable_fso_global,
    revert_disable_mpo,
    revert_disable_pointer_shadow,
    revert_disable_vbs,
    revert_distribute_timers,
    revert_dwm_animations_on,
    revert_energy_logging_on,
    revert_fth_on,
    revert_game_dvr_on,
    revert_game_mode_off,
    revert_game_profile,
    revert_gpu_energy_drv_on,
    revert_gpu_preemption,
    revert_gpu_power_latency_pack,
    revert_gpu_thread_priority,
    revert_graphics_latency,
    revert_gta5_priority,
    revert_hags,
    revert_hidusb_low_latency,
    revert_hibernate_on,
    revert_input_layered_latency,
    revert_io_page_lock_limit,
    revert_keyboard_fast_delays,
    revert_keyboard_queue_size,
    revert_latency_sensitive_games,
    revert_location_on,
    revert_maintenance_on,
    revert_memory_compression_on,
    revert_memory_gaming,
    revert_mmcss_aggressive,
    revert_monitor_latency,
    revert_mouse_default,
    revert_mouse_queue_size,
    revert_msi_gpu,
    revert_msi_network,
    revert_msi_usb,
    revert_ndu_on,
    revert_nic_power_on,
    revert_network_throttle_on,
    revert_notifications_on,
    revert_nvidia_driver_tweaks,
    revert_nvidia_telemetry_on,
    revert_nvidia_write_combining_on,
    revert_power_latency_pack,
    revert_power_throttling_on,
    revert_raw_input_priority,
    revert_high_performance_plan,
    revert_win32_priority_26,
    revert_ssd_trim_info,
    revert_telemetry_policies_on,
    revert_sysmain_on,
    revert_tcp_default,
    revert_transparency_on,
    revert_usb_selective_suspend_on,
    revert_valorant_priority,
    revert_widgets_on,
    revert_windowed_games_opt,
    revert_xbox_services_on,
)
from nvidia import apply_nvidia_profile_inspector, revert_nvidia_profile_info
import engine_extra as ex


@dataclass
class Tweak:
    id: str
    name: str
    tab: str
    description: str
    effects: list[str]
    risk: str
    reboot: bool
    apply_fn: Callable[[], tuple[bool, str]]
    revert_fn: Callable[[], tuple[bool, str]]
    default_on: bool = False
    preset_safe: bool = False
    preset_latency: bool = False
    preset_fps: bool = False
    preset_competitive: bool = False
    boot_risk: str | None = None  # "critical" | "warning"


TABS = {
    "latency": "Задержка",
    "fps": "FPS / GPU",
    "input": "Ввод",
    "system": "Система",
    "network": "Сеть",
    "nvidia": "NVIDIA / MSI",
    "games": "Игры",
    "privacy": "Приватность",
}


def _with_user_copy(tweaks: list[Tweak]) -> list[Tweak]:
    out: list[Tweak] = []
    for t in tweaks:
        br = get_boot_risk_level(t.id)
        if t.id in TWEAK_COPY:
            name, desc = TWEAK_COPY[t.id]
            recovery = boot_risk_recovery_line(t.id)
            if recovery:
                desc = f"{desc}\n\n{recovery}"
            out.append(replace(t, name=name, description=desc, boot_risk=br))
        else:
            out.append(replace(t, boot_risk=br))
    return out


@lru_cache(maxsize=1)
def _cached_all_tweaks() -> list[Tweak]:
    return _with_user_copy(_raw_tweaks())


def get_all_tweaks() -> list[Tweak]:
    return _cached_all_tweaks()


def _raw_tweaks() -> list[Tweak]:
    return [
        # ── Задержка ──
        Tweak("game_dvr", "Отключить Game DVR / Xbox Bar", "latency",
              "Выключает захват и оверлей. Снижает input lag и микрофризы. Calamity / opt.",
              ["latency", "fps", "freezes"], "low", False,
              apply_game_dvr_off, revert_game_dvr_on, True, True, True, True, True),
        Tweak("graphics_latency", "GPU Flip Queue (мин. буфер кадров)", "latency",
              "MaximumFrameLatency=1, FlipQueueSize=1. Меньше задержка, возможны просадки на слабом GPU. Juma.",
              ["latency"], "medium", False,
              apply_graphics_latency, revert_graphics_latency, True, False, True, False, True),
        Tweak("monitor_latency", "Толерантность задержки монитора", "latency",
              "MonitorLatencyTolerance=0 — Windows не терпит лишнюю задержку вывода. DXGKrnl.",
              ["latency"], "low", True,
              apply_monitor_latency, revert_monitor_latency, False, False, True, False, True),
        Tweak("mmcss", "Агрессивный MMCSS", "latency",
              "NoLazyMode + AlwaysOn + SystemResponsiveness=0. Больше CPU для активного окна. Calamity / xiaumm.",
              ["latency", "fps", "freezes"], "medium", False,
              apply_mmcss_aggressive, revert_mmcss_aggressive, False, False, True, True, True),
        Tweak("power_throttling", "Отключить Power Throttling", "latency",
              "Запрещает Windows снижать частоту CPU. Меньше случайных фризов.",
              ["latency", "fps", "freezes"], "low", False,
              apply_power_throttling_off, revert_power_throttling_on, True, True, True, True, True),
        Tweak("bcd_timer", "BCD: стабильный системный таймер", "latency",
              "disabledynamictick + useplatformtick. Juma / InpetLag.ps1. Перезагрузка.",
              ["latency"], "medium", True,
              apply_bcd_timer_tweaks, revert_bcd_timer_tweaks, False, False, True, False, True),
        Tweak("latency_sensitive", "Games: Latency Sensitive", "latency",
              "Помечает игровые задачи как чувствительные к задержке. xiaumm.",
              ["latency"], "low", False,
              apply_latency_sensitive_games, revert_latency_sensitive_games, False, False, True, False, True),
        Tweak("distribute_timers", "DistributeTimers (ядро)", "latency",
              "Распределение таймеров по ядрам — меньше contention. xiaumm.",
              ["latency", "freezes"], "low", True,
              apply_distribute_timers, revert_distribute_timers, False, False, True, False, False),
        Tweak("gpu_preemption", "GPU Preemption", "latency",
              "Разрешает прерывание длинных GPU-задач для рендера кадров. Современные игры.",
              ["latency", "freezes"], "medium", True,
              apply_gpu_preemption, revert_gpu_preemption, False, False, True, False, True),
        # ── FPS / GPU ──
        Tweak("game_profile", "Игровой профиль Windows", "fps",
              "GPU Priority=8, Priority=6, Scheduling=High. Boost FPS.reg / xiaumm.",
              ["fps", "freezes"], "low", False,
              apply_game_profile, revert_game_profile, True, True, False, True, True),
        Tweak("gpu_thread_priority", "Приоритет потоков GPU", "fps",
              "ThreadPriority=0x1F для NVIDIA/AMD драйвера. waylaa / opt.",
              ["fps", "freezes"], "low", True,
              apply_gpu_thread_priority, revert_gpu_thread_priority, False, False, False, True, True),
        Tweak("memory_gaming", "Оптимизация памяти", "fps",
              "DisablePagingExecutive + Superfetch off. Меньше обращений к диску.",
              ["fps", "freezes"], "low", True,
              apply_memory_gaming, revert_memory_gaming, False, False, False, True, False),
        Tweak("sysmain_off", "Отключить SysMain / Search", "fps",
              "Останавливает фоновую индексацию. Base.reg / xiaumm.",
              ["fps", "freezes"], "medium", False,
              apply_sysmain_off, revert_sysmain_on, False, False, False, True, False),
        Tweak("transparency", "Отключить прозрачность UI", "fps",
              "Режим производительности для окон Windows.",
              ["fps"], "low", False,
              apply_transparency_off, revert_transparency_on, False, True, False, True, False),
        Tweak("gpu_energy", "Отключить GpuEnergyDrv", "fps",
              "Меньше фоновых прерываний от учёта энергии GPU. xiaumm.",
              ["fps", "latency"], "low", True,
              apply_gpu_energy_drv_off, revert_gpu_energy_drv_on, False, False, False, True, False),
        Tweak("hags", "HAGS (аппаратное планирование GPU)", "fps",
              "HwSchMode=2 — Hardware-Accelerated GPU Scheduling. xiaumm. Эффект зависит от системы.",
              ["fps", "latency"], "medium", True,
              apply_hags, revert_hags, False, False, False, True, False),
        Tweak("game_mode", "Windows Game Mode", "fps",
              "Включает Game Mode (не Game Bar!). Приоритет ресурсов игре. xiaumm.",
              ["fps"], "low", False,
              apply_game_mode_on, revert_game_mode_off, True, True, False, True, True),
        Tweak("fth_off", "Отключить Fault Tolerant Heap", "fps",
              "FTH off — меньше оверхеда на аллокации. Calamity.",
              ["fps", "freezes"], "low", False,
              apply_fth_off, revert_fth_on, False, False, False, True, False),
        Tweak("energy_logging", "Отключить Energy Logging", "fps",
              "Меньше телеметрии питания в фоне. xiaumm.",
              ["fps"], "low", False,
              apply_energy_logging_off, revert_energy_logging_on, False, False, False, True, False),
        # ── Ввод ──
        Tweak("mouse_1to1", "Мышь 1:1 (без ускорения)", "input",
              "Линейная кривая, отключена «точность указателя». waylaa / Calamity.",
              ["latency"], "low", False,
              apply_mouse_1to1, revert_mouse_default, True, True, True, False, True),
        Tweak("usb_suspend", "USB Selective Suspend OFF", "input",
              "USB не уходит в сон — нет задержек мыши после простоя.",
              ["latency", "freezes"], "low", True,
              apply_usb_selective_suspend_off, revert_usb_selective_suspend_on, False, False, True, False, True),
        Tweak("usb_power", "USB Power Management OFF", "input",
              "Отключает энергосбережение USB root hub. X3 Team.",
              ["latency", "freezes"], "low", False,
              apply_usb_power_saving_off, lambda: (True, "Ручной сброс в диспетчере устройств"),
              False, False, True, False, True),
        # ── Система ──
        Tweak("cpu_priority", "Foreground CPU Priority", "system",
              "Win32PrioritySeparation=0x28. InputLag.reg / waylaa.",
              ["latency", "fps"], "low", False,
              apply_cpu_priority, revert_cpu_priority, False, False, True, True, True),
        Tweak("win32_priority_26", "Win32Priority 26 (киберспорт)", "system",
              "Значение 0x26 — баланс foreground/background, часто используют в esports-твиках.",
              ["latency", "fps"], "low", False,
              apply_win32_priority_26, revert_win32_priority_26,
              False, False, True, False, True),
        Tweak("background_apps", "Ограничить фоновые UWP", "system",
              "Меньше случайных скачков CPU/RAM от Store-приложений.",
              ["fps", "freezes"], "low", False,
              apply_background_apps_off, revert_background_apps_on, False, False, False, True, False),
        Tweak("maintenance", "Отключить автообслуживание", "system",
              "Предотвращает фоновое обслуживание во время игры.",
              ["freezes"], "low", False,
              apply_maintenance_off, revert_maintenance_on, False, False, False, True, False),
        Tweak("desktop_resp", "Быстрый отклик рабочего стола", "system",
              "MenuShowDelay=0, ForegroundLockTimeout=0. Base.reg.",
              ["latency"], "low", False,
              apply_desktop_responsiveness, revert_desktop_responsiveness, False, True, True, False, False),
        Tweak("hibernate_off", "Отключить гибернацию", "system",
              "Освобождает место на SSD и убирает hiberfil.sys. xiauopt.",
              ["fps"], "low", False,
              apply_hibernate_off, revert_hibernate_on, False, False, False, True, False),
        Tweak("notifications_off", "Отключить уведомления", "system",
              "Меньше всплывающих окон и звуков во время игры. xiauopt.",
              ["freezes", "latency"], "low", False,
              apply_notifications_off, revert_notifications_on, False, True, False, False, False),
        # ── Сеть ──
        Tweak("tcp_latency", "TCP Low Latency", "network",
              "TCPNoDelay + TcpAckFrequency=1. ⚠ Ускоряет мелкие игровые пакеты, но часто замедляет "
              "сайты, Discord, Majestic и любой HTTPS (много мелких TCP-запросов).",
              ["latency"], "low", False,
              apply_tcp_low_latency, revert_tcp_default, False, False, True, False, True),
        Tweak("network_throttle", "NetworkThrottlingIndex MAX", "network",
              "Отключает искусственное ограничение сети Windows (0xFFFFFFFF). "
              "Часто рекомендуют для онлайн-игр; на редких PC может поднять DPC — тестируйте.",
              ["latency"], "medium", False,
              apply_network_throttle_off, revert_network_throttle_on,
              False, False, True, False, True),
        Tweak("tcp_interfaces", "TCP NoDelay на всех адаптерах", "network",
              "TcpAckFrequency=1 на каждом адаптере. ⚠ Удваивает эффект tcp_latency — "
              "может сильно тормозить браузер, Discord и лаунчеры с web-UI.",
              ["latency"], "low", False,
              ex.apply_tcp_interface_nodelay, ex.revert_tcp_interface_nodelay,
              False, False, True, False, True),
        # ── NVIDIA / MSI ──
        Tweak("msi_gpu", "MSI Mode — видеокарта", "nvidia",
              "Message Signaled Interrupts + High priority для GPU. Calamity / xiaumm / Guru3D.",
              ["latency", "fps", "freezes"], "medium", True,
              apply_msi_gpu, revert_msi_gpu, True, False, True, True, True),
        Tweak("msi_usb", "MSI Mode — USB контроллер", "nvidia",
              "MSI для USB root hub — меньше DPC latency на вводе. xiaumm.",
              ["latency", "freezes"], "low", True,
              apply_msi_usb, revert_msi_usb, False, False, True, False, True),
        Tweak("msi_network", "MSI Mode — сетевая карта", "nvidia",
              "MSI для сетевого адаптера. xiaumm.",
              ["latency"], "low", True,
              apply_msi_network, revert_msi_network, False, False, True, False, True),
        Tweak("nvidia_profile", "NVIDIA Profile Inspector — Low Latency", "nvidia",
              "Применяет профиль: LLM Ultra, Prerendered=1, Max Performance, VSync Off, Ansel Off. "
              "Calamity / Ancel / valleyofdoom. Скачивает NPI при первом запуске.",
              ["latency", "fps"], "medium", False,
              apply_nvidia_profile_inspector, revert_nvidia_profile_info, False, False, True, True, True),
        Tweak("nvidia_driver", "NVIDIA Driver Tweaks", "nvidia",
              "DisplayPowerSaving off, Miracast off, nvidia-smi unrestricted clocks.",
              ["fps", "latency"], "medium", False,
              apply_nvidia_driver_tweaks, revert_nvidia_driver_tweaks, False, False, False, True, True),
        Tweak("nvidia_pstate", "DisableDynamicPstate (P0 lock)", "nvidia",
              "GPU не снижает P-state в простое. Выше idle power, ниже latency. xiauopt / PC-Tuning.",
              ["latency", "fps"], "medium", True,
              apply_disable_dynamic_pstate, revert_disable_dynamic_pstate, False, False, True, False, True),
        Tweak("nvidia_wc", "Disable Write Combining", "nvidia",
              "Calamity — меньше буферизации записи в драйвере NVIDIA.",
              ["latency"], "low", True,
              apply_nvidia_write_combining_off, revert_nvidia_write_combining_on, False, False, True, False, False),
        Tweak("nvidia_telemetry", "Отключить NVIDIA Telemetry", "nvidia",
              "Останавливает NvTelemetryContainer. Calamity.",
              ["fps", "freezes"], "low", False,
              apply_nvidia_telemetry_off, revert_nvidia_telemetry_on, False, True, False, False, False),
        # ── Игры ──
        Tweak("gta5_priority", "GTA5 — High CPU Priority", "games",
              "CpuPriorityClass=High через IFEO. opt / GTA tweak.",
              ["fps", "freezes"], "low", False,
              apply_gta5_priority, revert_gta5_priority, False, False, False, False, False),
        Tweak("cs2_priority", "CS2 — High CPU Priority", "games",
              "CpuPriorityClass=High для cs2.exe. xiauopt/cs2.reg.",
              ["fps", "freezes"], "low", False,
              apply_cs2_priority, revert_cs2_priority, False, False, False, False, True),
        # ── Доп. задержка ──
        Tweak("disable_mpo", "Отключить MPO (Multi-Plane Overlay)", "latency",
              "OverlayTestMode=5 — убирает оверлей DWM. ⚠ На 2+ мониторах часто ломает перенос окон мышью между экранами.",
              ["latency"], "medium", True,
              apply_disable_mpo, revert_disable_mpo, False, False, False, False, False),
        Tweak("disable_fso", "Отключить Fullscreen Optimizations", "latency",
              "Глобально отключает FSO для игр — меньше input lag в borderless/fullscreen.",
              ["latency", "fps"], "low", False,
              apply_disable_fso_global, revert_disable_fso_global, True, True, True, True, True),
        Tweak("pointer_shadow", "Отключить тень курсора", "input",
              "Мелкий визуальный оверхед — убирает тень указателя.",
              ["latency"], "low", False,
              apply_disable_pointer_shadow, revert_disable_pointer_shadow, False, False, True, False, False),
        # ── Доп. FPS / GPU ──
        Tweak("directx_tweaks", "DirectX registry tweaks", "fps",
              "EmulationOnly=0, аппаратный Direct3D. PowerShell gaming guides.",
              ["fps"], "low", False,
              apply_directx_tweaks, revert_directx_tweaks, False, False, False, True, False),
        Tweak("dwm_animations", "Отключить анимации DWM", "fps",
              "MinAnimate off, TaskbarAnimations off — меньше нагрузки на композитор.",
              ["fps"], "low", False,
              apply_dwm_animations_off, revert_dwm_animations_on, False, True, False, True, False),
        # ── Доп. система ──
        Tweak("core_parking", "Отключить Core Parking", "system",
              "Все ядра активны 100% времени на High Performance. Меньше stutter при нагрузке.",
              ["fps", "freezes"], "low", False,
              apply_core_parking_off, revert_core_parking_on, False, False, False, True, True),
        Tweak("ultimate_power", "Ultimate Performance план", "system",
              "Максимальный план питания Windows — выше отзывчивость CPU.",
              ["fps", "latency"], "low", False,
              apply_ultimate_power_plan, revert_high_performance_plan, False, False, False, True, True),
        Tweak("disable_cstates", "Снизить C-States CPU", "system",
              "Меньше глубоких состояний простоя CPU — ниже latency, выше idle power.",
              ["latency", "fps"], "medium", True,
              apply_disable_cstates, revert_disable_cstates, False, False, True, True, True),
        Tweak("diagtrack_off", "Отключить DiagTrack", "system",
              "Служба телеметрии Windows — меньше фоновой нагрузки.",
              ["fps", "freezes"], "low", False,
              apply_diagtrack_off, revert_diagtrack_on, False, True, False, True, False),
        Tweak("ndu_off", "Отключить NDU", "system",
              "Network Diagnostic Usage — частая причина DPC latency spikes.",
              ["latency", "freezes"], "low", True,
              apply_ndu_off, revert_ndu_on, False, False, True, False, True),
        Tweak("delivery_opt_off", "Отключить Delivery Optimization", "system",
              "Windows не раздаёт обновления в фоне — меньше сетевой/дисковой нагрузки.",
              ["fps", "freezes"], "low", False,
              apply_delivery_optimization_off, revert_delivery_optimization_on, False, True, False, False, False),
        Tweak("disable_vbs", "Отключить VBS / Memory Integrity", "system",
              "Virtualization-Based Security off. До +5-10% FPS. Снижает безопасность. 2026 guides.",
              ["fps"], "high", True,
              apply_disable_vbs, revert_disable_vbs, False, False, False, True, False),
        Tweak("content_delivery", "Отключить рекламу Windows", "system",
              "Suggestions, SoftLanding, SubscribedContent — меньше фоновых задач.",
              ["fps", "freezes"], "low", False,
              apply_content_delivery_off, revert_content_delivery_on, False, True, False, False, False),
        Tweak("xbox_services", "Отключить службы Xbox", "system",
              "XblAuth, GameSave, XboxNet — если не используете Xbox / Game Bar.",
              ["fps"], "low", False,
              apply_xbox_services_off, revert_xbox_services_on, False, True, False, True, False),
        Tweak("csrss_prio", "CSRSS High Priority", "system",
              "Повышенный приоритет подсистемы Win32. xiaumm. Используйте осторожно.",
              ["latency", "freezes"], "medium", False,
              apply_csrss_priority, revert_csrss_priority, False, False, True, False, False),
        Tweak("auto_end_tasks", "AutoEndTasks + короткие таймауты", "system",
              "Быстрее закрытие зависших процессов — меньше блокировок.",
              ["freezes"], "low", False,
              apply_auto_end_tasks, revert_auto_end_tasks, False, False, False, False, False),
        # ── Доп. сеть ──
        Tweak("nic_power_off", "NIC Power Saving OFF", "network",
              "Отключает энергосбережение сетевой карты — стабильнее ping.",
              ["latency", "freezes"], "low", False,
              apply_nic_power_off, revert_nic_power_on, False, False, True, False, True),
        Tweak("defender_off", "Полное отключение Windows Defender", "system",
              "DisableAntiSpyware, Real-Time Protection off, WinDefend/WdNisSvc stopped. "
              "Anti.reg / Ancels batch. Снижает фоновую нагрузку. Высокий риск без другого AV.",
              ["fps", "freezes"], "high", True,
              apply_defender_off, revert_defender_on, False, False, False, True, False),
        # ── GitHub / форумы: shoober420, Atlas, Win11Debloat ──
        Tweak("gpu_power_latency", "GPU Power Latency Pack", "fps",
              "LOWLATENCY, D3PCLatency, ForceLowLatencyDisplayMode — shoober420 GPUTweaks. "
              "Меньше задержка GPU, возможна чуть ниже энергоэффективность.",
              ["latency", "fps"], "medium", True,
              apply_gpu_power_latency_pack, revert_gpu_power_latency_pack,
              False, False, True, True, True),
        Tweak("power_latency_pack", "Power Latency Pack", "latency",
              "ExitLatency, CsEnabled=0, QosManagesIdleProcessors — shoober420 / TGO.",
              ["latency", "freezes"], "medium", True,
              apply_power_latency_pack, revert_power_latency_pack,
              False, False, True, True, False),
        Tweak("windowed_games", "Оптимизация оконных игр", "fps",
              "SwapEffectUpgradeEnable + Auto Game Mode — гайды Win11 2025/2026, DirectX.",
              ["fps", "latency"], "low", False,
              apply_windowed_games_opt, revert_windowed_games_opt,
              True, True, True, True, True),
        Tweak("memory_compression_off", "Отключить сжатие RAM", "system",
              "EnableCompressedMemory=0 + Disable-MMAgent. Atlas / форумы — меньше микрофризов при нехватке RAM.",
              ["freezes", "fps"], "medium", True,
              apply_memory_compression_off, revert_memory_compression_on,
              False, False, True, False, False),
        Tweak("page_combining_off", "DisablePageCombining", "system",
              "Отключает объединение страниц памяти — игровые пакеты оптимизации.",
              ["latency", "freezes"], "medium", False,
              apply_disable_page_combining, revert_disable_page_combining,
              False, False, False, True, False),
        Tweak("io_page_lock", "IoPageLockLimit", "system",
              "983040 (0xF0000) — больше locked pages для I/O. Atlas / Calamity.",
              ["fps", "freezes"], "low", False,
              apply_io_page_lock_limit, revert_io_page_lock_limit,
              False, False, True, False, False),
        Tweak("audio_mmcss_pro", "MMCSS Pro Audio", "latency",
              "Высокий приоритет аудио-потока — Win11 gaming optimizer, меньше audio stutter.",
              ["latency", "freezes"], "low", False,
              apply_audio_mmcss_pro, revert_audio_mmcss_pro,
              False, True, False, True, False),
        Tweak("ssd_trim", "SSD TRIM + оптимизация", "system",
              "fsutil DisableDeleteNotify=0 + defrag /O. Реально работает на SSD/NVMe.",
              ["fps", "freezes"], "low", False,
              apply_ssd_trim, revert_ssd_trim_info,
              True, False, True, False, False),
        Tweak("spooler_off", "Отключить Print Spooler", "system",
              "Меньше фоновых процессов — Batlez / TGO (если не печатаете).",
              ["fps"], "low", False,
              apply_disable_print_spooler, revert_disable_print_spooler,
              False, False, True, False, False),
        # ── Ввод: shoober420 InputTweaks ──
        Tweak("hidusb_latency", "HidUsb Low Latency", "input",
              "ForceLowLatencyMode, DisableSelectiveSuspend — USB мышь/клавиатура.",
              ["latency"], "medium", True,
              apply_hidusb_low_latency, revert_hidusb_low_latency,
              False, True, False, True, True),
        Tweak("raw_input_prio", "Raw Input High Priority", "input",
              "EnableRawInputHighPriority + MOUSE_RAW_INPUT — shoober420.",
              ["latency"], "low", False,
              apply_raw_input_priority, revert_raw_input_priority,
              False, True, False, True, True),
        Tweak("layered_latency", "LayeredLatency = 0", "input",
              "kbdclass/mouclass/kbdhid/mouhid — убирает слой буферизации ввода.",
              ["latency"], "medium", True,
              apply_input_layered_latency, revert_input_layered_latency,
              False, True, False, True, True),
        Tweak("keyboard_fast", "Быстрая клавиатура", "input",
              "KeyboardDelay=3, KeyboardSpeed=31 — быстрый повтор Backspace и стрелок. "
              "⚠ Старые версии ставили 0/0 и делали стирание очень медленным.",
              ["latency"], "low", False,
              apply_keyboard_fast_delays, revert_keyboard_fast_delays,
              False, True, False, True, True),
        Tweak("cursor_fast", "Быстрое обновление курсора", "input",
              "CursorUpdateInterval=1 — shoober420 InputTweaks.",
              ["latency"], "low", False,
              apply_cursor_fast_update, revert_cursor_fast_update,
              False, True, False, True, False),
        # ── Сеть ──
        Tweak("dns_cloudflare", "DNS Cloudflare (1.1.1.1)", "network",
              "Ставит 1.1.1.1 на ВСЕ адаптеры, включая VPN (Radmin и др.). "
              "⚠ Если VPN активен с высоким приоритетом — DNS и сайты могут грузиться очень долго.",
              ["latency"], "low", False,
              apply_dns_cloudflare, revert_dns_dhcp,
              False, False, True, True, True),
        # ── Приватность / debloat ──
        Tweak("telemetry_off", "Телеметрия OFF", "privacy",
              "AllowTelemetry=0, dmwappushservice — Sophia / Win11Debloat / Atlas.",
              ["fps", "freezes"], "low", False,
              apply_telemetry_policies_off, revert_telemetry_policies_on,
              True, False, True, False, False),
        Tweak("cortana_off", "Отключить Cortana", "privacy",
              "AllowCortana=0 — Win11Debloat.",
              ["fps"], "low", False,
              apply_cortana_off, revert_cortana_on,
              True, False, True, False, False),
        Tweak("error_report_off", "Отключить Error Reporting", "privacy",
              "WerSvc + политики — меньше фоновых отчётов при крашах.",
              ["freezes", "fps"], "low", False,
              apply_error_reporting_off, revert_error_reporting_on,
              False, False, True, False, False),
        Tweak("widgets_off", "Виджеты / лента OFF", "privacy",
              "TaskbarDa + AllowNewsAndInterests — Win11Debloat.",
              ["fps"], "low", False,
              apply_widgets_off, revert_widgets_on,
              True, False, True, False, False),
        Tweak("location_off", "Геолокация OFF", "privacy",
              "DisableLocation + lfsvc — меньше фоновых служб.",
              ["fps"], "low", False,
              apply_location_off, revert_location_on,
              True, False, False, False, False),
        # ── +30 твиков: Atlas, Win11Debloat, Sophia, форумы ──
        Tweak("fast_startup_off", "Отключить Fast Startup", "system",
              "HiberbootEnabled=0 — меньше странных багов после выключения. Рекомендуют форумы 2025.",
              ["freezes", "latency"], "low", False,
              ex.apply_fast_startup_off, ex.revert_fast_startup_on,
              True, False, False, False, False),
        Tweak("llmnr_off", "Отключить LLMNR", "network",
              "Multicast DNS off — меньше сетевого шума и задержек в LAN.",
              ["latency"], "low", False,
              ex.apply_llmnr_off, ex.revert_llmnr_on,
              False, False, True, False, False),
        Tweak("netbios_off", "NetBIOS over TCP/IP OFF", "network",
              "На всех адаптерах — Atlas / competitive network guides.",
              ["latency"], "low", False,
              ex.apply_netbios_off, ex.revert_netbios_on,
              False, False, True, False, False),
        Tweak("sticky_keys_off", "Отключить Sticky/Filter Keys", "input",
              "Нет случайного залипания Shift/Ctrl при игре.",
              ["latency"], "low", False,
              ex.apply_sticky_keys_off, ex.revert_sticky_keys_on,
              True, False, False, False, False),
        Tweak("mouse_trails_off", "Отключить шлейф мыши", "input",
              "MouseTrails=0 — чуть меньше визуальной задержки курсора.",
              ["latency"], "low", False,
              ex.apply_mouse_trails_off, ex.revert_mouse_trails_on,
              False, True, False, False, False),
        Tweak("lock_blur_off", "Blur экрана блокировки OFF", "fps",
              "Меньше GPU на экране входа — Win11Debloat.",
              ["fps"], "low", False,
              ex.apply_lock_screen_blur_off, ex.revert_lock_screen_blur_on,
              False, True, False, False, False),
        Tweak("activity_hist_off", "Activity History OFF", "privacy",
              "PublishUserActivities off — Sophia / Atlas.",
              ["fps"], "low", False,
              ex.apply_activity_history_off, ex.revert_activity_history_on,
              True, False, False, False, False),
        Tweak("storage_sense_off", "Storage Sense OFF", "system",
              "Windows не чистит диск в фоне во время игры.",
              ["freezes", "fps"], "low", False,
              ex.apply_storage_sense_off, ex.revert_storage_sense_on,
              False, False, True, False, False),
        Tweak("remote_assist_off", "Remote Assistance OFF", "privacy",
              "fAllowToGetHelp=0 — закрывает удалённую помощь.",
              ["fps"], "low", False,
              ex.apply_remote_assistance_off, ex.revert_remote_assistance_on,
              True, False, False, False, False),
        Tweak("pca_off", "Program Compatibility Assistant OFF", "system",
              "PcaSvc disabled — меньше фоновых проверок exe.",
              ["fps", "freezes"], "low", False,
              ex.apply_pca_off, ex.revert_pca_on,
              False, False, True, False, False),
        Tweak("onedrive_policy", "OneDrive sync policy OFF", "privacy",
              "DisableFileSyncNGSC — если не используете OneDrive.",
              ["fps"], "low", False,
              ex.apply_onedrive_policy_off, ex.revert_onedrive_policy_on,
              False, False, True, False, False),
        Tweak("bluetooth_off", "Bluetooth службы OFF", "system",
              "Если BT не нужен — меньше фоновых служб.",
              ["fps"], "low", False,
              ex.apply_bluetooth_off, ex.revert_bluetooth_on,
              False, False, True, False, False),
        Tweak("wlan_off", "Wi-Fi служба OFF", "network",
              "Только при Ethernet! Иначе потеряете Wi-Fi.",
              ["latency", "fps"], "medium", False,
              ex.apply_wlan_off, ex.revert_wlan_on,
              False, False, False, False, False),
        Tweak("ntfs_last_access", "NTFS Last Access OFF", "system",
              "fsutil disablelastaccess=1 — меньше записей на диск.",
              ["fps", "freezes"], "low", True,
              ex.apply_ntfs_last_access_off, ex.revert_ntfs_last_access_on,
              False, False, True, False, False),
        Tweak("web_search_off", "Поиск Bing в панели OFF", "privacy",
              "DisableWebSearch — локальный поиск только.",
              ["fps"], "low", False,
              ex.apply_web_search_off, ex.revert_web_search_on,
              True, False, True, False, False),
        Tweak("smartscreen_off", "SmartScreen OFF", "privacy",
              "Снижает проверки загрузок. Высокий риск безопасности.",
              ["fps", "latency"], "high", False,
              ex.apply_smartscreen_off, ex.revert_smartscreen_on,
              False, False, False, False, False),
        Tweak("maps_broker_off", "MapsBroker OFF", "system",
              "Служба карт — фоновая геолокация.",
              ["fps"], "low", False,
              ex.apply_maps_broker_off, ex.revert_maps_broker_on,
              False, False, True, False, False),
        Tweak("fax_off", "Fax OFF", "system",
              "Устаревшая служба факса.",
              ["fps"], "low", False,
              ex.apply_fax_off, ex.revert_fax_on,
              False, False, True, False, False),
        Tweak("remote_registry_off", "Remote Registry OFF", "privacy",
              "Закрывает удалённый доступ к реестру.",
              ["fps"], "low", False,
              ex.apply_remote_registry_off, ex.revert_remote_registry_on,
              True, False, False, False, False),
        Tweak("consumer_features", "Consumer Features OFF", "privacy",
              "Блок suggested apps / реклама в меню Пуск.",
              ["fps", "freezes"], "low", False,
              ex.apply_consumer_features_off, ex.revert_consumer_features_on,
              True, False, True, False, False),
        Tweak("chat_taskbar_off", "Chat (Teams) на панели OFF", "privacy",
              "TaskbarMn=0 — Win11Debloat.",
              ["fps"], "low", False,
              ex.apply_chat_taskbar_off, ex.revert_chat_taskbar_on,
              True, False, False, False, False),
        Tweak("snap_assist_off", "Snap Assist OFF", "fps",
              "Меньше оверлеев при перетаскивании окон.",
              ["fps"], "low", False,
              ex.apply_snap_assist_off, ex.revert_snap_assist_on,
              False, True, False, False, False),
        Tweak("edge_startup_off", "Edge Startup Boost OFF", "system",
              "Edge не стартует в фоне — Win11Debloat.",
              ["fps"], "low", False,
              ex.apply_edge_startup_off, ex.revert_edge_startup_on,
              False, True, False, False, False),
        Tweak("insider_off", "Windows Insider OFF", "system",
              "wisvc disabled.",
              ["fps"], "low", False,
              ex.apply_insider_service_off, ex.revert_insider_service_on,
              False, False, True, False, False),
        Tweak("gamebar_presence", "Game Bar Presence OFF", "latency",
              "GameBarPresence=0 — меньше оверлея Xbox.",
              ["latency", "fps"], "low", False,
              ex.apply_gamebar_presence_off, ex.revert_gamebar_presence_on,
              True, True, True, True, True),
        Tweak("gamebar_policy", "Game DVR policy OFF", "latency",
              "Групповая политика AllowGameDVR=0 — полностью отключает захват Xbox. "
              "Один из самых стабильных твиков по отзывам.",
              ["latency", "fps"], "low", False,
              ex.apply_gamebar_policy_off, ex.revert_gamebar_policy_on,
              True, True, True, True, True),
        Tweak("visual_performance", "Максимальная производительность UI", "fps",
              "DragFullWindows=0 — при перетаскивании только контур окна. VisualFXSetting=2, без прозрачности.",
              ["fps"], "low", False,
              ex.apply_visual_performance_max, ex.revert_visual_performance_max,
              True, True, False, True, False),
        Tweak("wsearch_off", "Отключить индексацию Windows Search", "system",
              "Служба WSearch off — меньше фоновых обращений к диску. Поиск в Пуске станет медленнее.",
              ["fps", "freezes"], "medium", False,
              ex.apply_wsearch_off, ex.revert_wsearch_on,
              False, False, True, False, False),
        # --- Дополнительные твики (engine + Atlas / WinUtil / форумы) ---
        Tweak("prefetch_off", "Отключить Prefetcher", "system",
              "EnablePrefetcher=0 — меньше фоновых чтений диска. По отзывам на SSD снижает микрофризы в играх.",
              ["fps", "freezes"], "low", False,
              apply_disable_prefetch_gaming, revert_disable_prefetch_gaming,
              False, True, True, False, False),
        Tweak("superfetch_off", "Отключить Superfetch", "system",
              "Prefetch + Superfetch off — популярный твик для игровых SSD. Поиск файлов может стать медленнее.",
              ["fps", "freezes"], "medium", False,
              ex.apply_superfetch_off, ex.revert_superfetch_on,
              False, False, True, False, False),
        Tweak("sysmain_svc_off", "Служба SysMain OFF", "system",
              "Полностью останавливает Superfetch-службу. Часто рекомендуют вместе с prefetch.",
              ["fps", "freezes"], "medium", False,
              ex.apply_sysmain_service_off, ex.revert_sysmain_service_on,
              False, False, True, False, False),
        Tweak("hpet_bcd", "BCD: отключить динамический тик", "latency",
              "disabledynamictick=yes — стабильнее таймер на части систем. Перезагрузка обязательна.",
              ["latency", "fps"], "medium", True,
              apply_disable_hpet_bcd, revert_disable_hpet_bcd,
              False, True, False, True, False),
        Tweak("hpet_platform", "BCD: useplatformtick", "latency",
              "useplatformtick=yes — альтернатива HPET-твикам. Эффект зависит от CPU/чипсета. Перезагрузка.",
              ["latency"], "medium", True,
              ex.apply_hpet_platform_tick, ex.revert_hpet_platform_tick,
              False, True, False, True, False),
        Tweak("hpet_service_off", "Служба HPET OFF", "latency",
              "Отключает High Precision Event Timer. На части ПК снижает input lag, на других — наоборот.",
              ["latency"], "medium", True,
              ex.apply_hpet_service_off, ex.revert_hpet_service_on,
              False, True, False, True, False),
        Tweak("mouse_queue", "MouseDataQueueSize = 22", "input",
              "Увеличивает буфер мыши — один из самых популярных input-твиков в esports-сообществах.",
              ["latency"], "low", False,
              apply_mouse_queue_size, revert_mouse_queue_size,
              True, True, True, True, True),
        Tweak("keyboard_queue", "KeyboardDataQueueSize = 22", "input",
              "Больший буфер клавиатуры — меньше потерянных нажатий при высокой нагрузке CPU.",
              ["latency"], "low", False,
              apply_keyboard_queue_size, revert_keyboard_queue_size,
              True, True, True, True, True),
        Tweak("large_system_cache", "LargeSystemCache", "system",
              "Профиль кэша «сервер» — иногда помогает RAM ≥16 ГБ в тяжёлых играх. Тестируйте FPS.",
              ["fps"], "medium", True,
              ex.apply_large_system_cache_on, ex.revert_large_system_cache_off,
              False, False, True, False, False),
        Tweak("spectre_mitigations", "Отключить Spectre/Meltdown", "fps",
              "FeatureSettingsOverride=3 — заметный прирост FPS, но снижает безопасность. Только для игровых ПК.",
              ["fps"], "high", True,
              ex.apply_spectre_meltdown_off, ex.revert_spectre_meltdown_on,
              False, False, True, False, True),
        Tweak("tsx_off", "Отключить Intel TSX", "latency",
              "bcdedit tsx off — убирает микростаттеры на старых Intel. Не поддерживается на всех CPU.",
              ["latency", "freezes"], "medium", True,
              ex.apply_tsx_off, ex.revert_tsx_on,
              False, True, False, True, False),
        Tweak("svchost_ungroup", "Svchost без группировки", "system",
              "SvcHostSplitThresholdInKB=0 — меньше «склеенных» svchost, иногда стабильнее фон.",
              ["fps", "freezes"], "medium", True,
              ex.apply_svchost_ungroup, ex.revert_svchost_ungroup,
              False, False, True, False, False),
        Tweak("transparency_blur", "Blur и прозрачность OFF", "fps",
              "ForceEffectMode=0 + прозрачность off — легче DWM, меньше нагрузки на GPU в меню.",
              ["fps"], "low", False,
              ex.apply_transparency_blur_off, ex.revert_transparency_blur_on,
              True, True, True, False, False),
        Tweak("explorer_anim_off", "Анимации проводника OFF", "fps",
              "MinAnimate=0, без теней списков — быстрее открытие папок и меню Пуска.",
              ["fps"], "low", False,
              ex.apply_explorer_animations_off, ex.revert_explorer_animations_on,
              True, True, True, False, False),
        Tweak("mmcss_games", "MMCSS профиль Games", "latency",
              "GPU Priority 8 для игр — усиленный профиль мультимедиа Windows. Часто хвалят в CS2/Valorant.",
              ["latency", "fps"], "low", False,
              ex.apply_mmcss_games_priority, ex.revert_mmcss_games_priority,
              True, True, True, True, True),
        Tweak("valorant_priority", "Valorant — High CPU Priority", "games",
              "Приоритет процесса VALORANT-Win64-Shipping.exe — меньше просадок при фоновых задачах.",
              ["fps", "latency"], "low", False,
              apply_valorant_priority, revert_valorant_priority,
              False, True, True, True, False),
        Tweak("usb_hub_suspend", "USB Hub Selective Suspend OFF", "input",
              "Отключает энергосбережение на USB-устройствах — стабильнее мышь/контроллер.",
              ["latency"], "low", False,
              ex.apply_disable_usb_hub_suspend, ex.revert_disable_usb_hub_suspend,
              True, True, True, True, False),
        Tweak("welcome_off", "Welcome Experience OFF", "privacy",
              "Убирает советы и «мягкую посадку» при первом входе — меньше фоновых загрузок.",
              ["fps"], "low", False,
              ex.apply_welcome_experience_off, ex.revert_welcome_experience_on,
              True, False, False, False, False),
        Tweak("search_highlights_off", "Search Highlights OFF", "privacy",
              "Отключает рекламные блоки в поиске Windows 11.",
              ["fps"], "low", False,
              ex.apply_search_highlights_off, ex.revert_search_highlights_on,
              True, False, False, False, False),
        Tweak("tips_off", "Советы Windows OFF", "privacy",
              "DisableSoftLanding + consumer features — меньше подсказок Microsoft в системе.",
              ["fps"], "low", False,
              ex.apply_tips_suggestions_off, ex.revert_tips_suggestions_on,
              True, False, False, False, False),
        Tweak("shared_exp_off", "Shared Experiences OFF", "privacy",
              "EnableCdp=0 — синхронизация активности между устройствами отключена.",
              ["fps"], "low", False,
              ex.apply_shared_experiences_off, ex.revert_shared_experiences_on,
              True, False, False, False, False),
        Tweak("tailored_off", "Tailored Experiences OFF", "privacy",
              "Не использовать диагностику для персонализации рекламы Windows.",
              ["fps"], "low", False,
              ex.apply_tailored_experiences_off, ex.revert_tailored_experiences_on,
              True, False, False, False, False),
        Tweak("news_off", "News and Interests OFF", "privacy",
              "EnableFeeds=0 — виджет новостей и лента на панели задач отключены.",
              ["fps"], "low", False,
              ex.apply_news_interests_off, ex.revert_news_interests_on,
              True, False, False, False, False),
        Tweak("store_autoupdate_off", "Store Auto-Update OFF", "system",
              "Microsoft Store не качает обновления UWP в фоне — меньше скачков диска.",
              ["fps", "freezes"], "low", False,
              ex.apply_store_auto_update_off, ex.revert_store_auto_update_on,
              False, False, True, False, False),
        Tweak("ntfs_8dot3_off", "NTFS 8.3 имена OFF", "system",
              "fsutil disable8dot3 — быстрее работа с большим числом файлов на SSD.",
              ["fps"], "low", True,
              ex.apply_ntfs_8dot3_off, ex.revert_ntfs_8dot3_on,
              False, False, True, False, False),
        Tweak("feedback_ceip_off", "Feedback / CEIP OFF", "privacy",
              "Не спрашивать отзывы и не отправлять CEIP-данные — меньше фоновых задач.",
              ["fps"], "low", False,
              ex.apply_feedback_ceip_off, ex.revert_feedback_ceip_on,
              True, False, False, False, False),
        Tweak("bits_off", "BITS OFF", "system",
              "Background Intelligent Transfer — фоновые загрузки Windows Update/Store. Освобождает канал и диск.",
              ["fps", "freezes"], "medium", False,
              ex.apply_background_transfer_off, ex.revert_background_transfer_on,
              False, False, True, False, False),
    ]

_SKIP_PRESET_ALL = frozenset({
    "nvidia_profile",
    "ssd_trim",
    "defender_off",
    "disable_vbs",
    "smartscreen_off",
    # Спорные/сильно железо-зависимые твики не включаем в «Рекомендуемые» автоматически.
    "disable_fso",
    "disable_mpo",
    "gpu_preemption",
    "memory_compression_off",
    "page_combining_off",
    "io_page_lock",
    "gpu_power_latency",
    "power_latency_pack",
    "spectre_mitigations",
    "hpet_bcd",
    "hpet_platform",
    "hpet_service_off",
    "tsx_off",
    "bits_off",
    "large_system_cache",
})


PRESETS = {
    "safe": ("Безопасный", lambda t: t.preset_safe),
    "latency": ("Мин. задержка", lambda t: t.preset_latency),
    "fps": ("Макс. FPS", lambda t: t.preset_fps),
    "competitive": ("Киберспорт", lambda t: t.preset_competitive),
    "all": (
        "Рекомендуемые",
        lambda t: (
            (t.preset_safe or t.preset_latency or t.preset_fps or t.preset_competitive)
            and t.id not in _SKIP_PRESET_ALL
            and t.risk != "high"
            and t.boot_risk != "critical"
        ),
    ),
    "none": ("Выключить все", lambda t: False),
}
